### PR TITLE
Extension in order to support Service Level Objectives

### PR DESCRIPTION
**Pull request by bluzukk**
# Description
This pull request extends the MeasurementsUI to support the creation and editing of service level objectives.

This work is the result of a Bachelor 'Fachstudie', which was done at the Reliable Software Systems Group at the University of Stuttgart. 
The goal was to increase the usability of service level objectives in the Palladio-Simulator by integrating them into the MeasurementsUI.

The pull request contains the following features:
- Tight integration of SLOs with the existing Measurement Dashboard
- Wizard based interface for defining normal and linear fuzzy Thresholds
- Graphical view of Thresholds during creation and viewing
- Filtering and Search of SLOs

# Issues
- SWT Chart needs to be installed manually (will break maven!)

### CODE REVIEW

**Comment by klinakuf** [comment]
@marfraTUC can you have a look on this?

**Comment by seiferma** [comment]
@bluzukk We cannot merge pull requests that break the build. We cannot have a closer look at your pull request before you fix the build.

What is the issue with fixing the build? There seems to be an [update site](https://download.eclipse.org/swtchart/0.7.0/release/) for SWTChart that can be integrated into the [target platform definition](https://github.com/PalladioSimulator/Palladio-Addons-MeasurementsUI/blob/master/releng/org.palladiosimulator.measurementsui.targetplatform/tp.target) of this project. This should fix the [build error](https://build.palladio-simulator.com/job/PalladioSimulator/job/Palladio-Addons-MeasurementsUI/job/PR-187/2/console).

**Comment by seiferma** [comment]
Because MeasurementsUI is part of our aggregated update site, there has to be another pull request in the [update site project](https://github.com/PalladioSimulator/Palladio-Build-UpdateSite) that adds the SWTChart update site to the [considered repositories](https://github.com/PalladioSimulator/Palladio-Build-UpdateSite/blob/master/palladiosimulator.aggr). If you are not familar with the CBI aggregator, you can give me a hint to integrate it. Nevertheless, we have to integrate the update site before merging this PR or the update site build will fail.

**Comment by bluzukk** [comment]
Hello @seiferma, I added the SWTChart to the target platform definition (6ccd21ac4146be2d84444a842cdae5d8703e8494) and it is building now successfully on my local machine.

I am not quite sure where to add SWTChart in the [update site project](https://github.com/PalladioSimulator/Palladio-Build-UpdateSite) could you please help me with this?

**Comment by seiferma** [comment]
Yes, now it works.

I created the pull request for the update site: PalladioSimulator/Palladio-Build-UpdateSite#21

**Comment by bluzukk** [comment]
Nice, thank you for your help.

**Comment by marfraTUC** [comment]
I had a short look at the code. It looks ok to me. However, I learned from their final presentation, that they were not using checkStyle and did not write test cases. So, I suggest to check the code against your checkStyle rules. There were plenty of checkStyle warnings during the build. Most of them seem to be harmless. So, I approve.

**Comment by seiferma** [comment]
@bluzukk Please merge the master branch into your fork and solve merging conflicts. We cannot merge the PR in the current state.

**Comment by bluzukk** [comment]
Done in commit 531397a4b2f16572af333a274509474cd2ef56f3.

**Pull request merged**
